[project]
name = "assignment-01"
version = "0.1.0"
description = ""
authors = [
    {name = "zeeshan",email = "zeeshanraza252627@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard] (>=0.115.11,<0.116.0)",
    "uvicorn (>=0.34.0,<0.35.0)"
]

